language: cpp
compiler:
  - gcc
  - clang
before_install:
  - echo $LANG
  - echo $LC_ALL
before_script:
script: make test
branches:
  only:
    - master
notifications:
  recipients:
    - sparkprime@gmail.com
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#jsonnet"
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
os:
  - linux
  - osx
