Document: jsonnet
Title: Debian jsonnet Manual
Author: <insert document author here>
Abstract: This manual describes what jsonnet is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/jsonnet/jsonnet.sgml.gz

Format: postscript
Files: /usr/share/doc/jsonnet/jsonnet.ps.gz

Format: text
Files: /usr/share/doc/jsonnet/jsonnet.text.gz

Format: HTML
Index: /usr/share/doc/jsonnet/html/index.html
Files: /usr/share/doc/jsonnet/html/*.html
